export const APP_ROUTES = {
  HOME: '/',
  PUBLIC: {
    CONTACT: '/contact',
    TERMS: '/conditions',
    ABOUT: '/qui-sommes-nous',
    JOB: (id: string) => `/offres/${id}`,
    COMPANY: (id: string) => `/entreprises/${id}`,
    TRAINING_CENTERS: '/centres-formation',
    TRAINING_CENTER: (id: string) => `/centres-formation/${id}`,
    TRAINING_CENTER_REGISTER: '/centres-formation/inscription',
    FORMATION: (id: string) => `/centres-formation/formations/${id}`,
    EVENT: (id: string) => `/centres-formation/evenements/${id}`,
    PRIVATE_INSTITUTIONS: '/etablissements-prives',
    PRIVATE_INSTITUTION: (id: string) => `/etablissements-prives/${id}`,
    PRIVATE_INSTITUTION_PUBLICATION: (id: string) => `/etablissements-prives/publications/${id}`,
    PRIVATE_INSTITUTION_REGISTER: '/etablissements-prives/inscription',
  },
  PROVIDER: {
    TRAINING: '/provider/centre',
    TRAINING_DASHBOARD: '/provider/centre/dashboard',
    TRAINING_PROFILE: '/provider/centre/profil',
    TRAINING_FORMATION_NEW: '/provider/centre/formations/nouveau',
    TRAINING_FORMATION_EDIT: (id: string) => `/provider/centre/formations/${id}`,
    TRAINING_EVENT_NEW: '/provider/centre/evenements/nouveau',
    TRAINING_EVENT_EDIT: (id: string) => `/provider/centre/evenements/${id}`,
    TRAINING_PARTICIPANTS: '/provider/centre/participants',
    INSTITUTION: '/provider/etablissement',
    INSTITUTION_DASHBOARD: '/provider/etablissement/dashboard',
    INSTITUTION_PROFILE: '/provider/etablissement/profil',
    INSTITUTION_PROGRAMS: '/provider/etablissement/programmes',
    INSTITUTION_EVENTS: '/provider/etablissement/evenements',
    INSTITUTION_ANNOUNCEMENTS: '/provider/etablissement/annonces',
    INSTITUTION_PUBLICATION_EDIT: (id: string) => `/provider/etablissement/publications/${id}`,
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
  },
  SETTINGS: '/settings',
  CANDIDATE: {
    ROOT: '/candidate',
    DASHBOARD: '/candidate/dashboard',
    JOBS: '/candidate/jobs',
    SAVED: '/candidate/saved',
    PROFILE: '/candidate/profile',
    SETTINGS: '/candidate/settings',
    COMPANY_DIRECTORY: '/candidate/annuaire-societes',
    TRAINING_DIRECTORY: '/candidate/annuaire-formations',
    INSTITUTION_DIRECTORY: '/candidate/annuaire-etablissements',
  },
  RECRUITER: {
    ROOT: '/recruiter',
    DASHBOARD: '/recruiter/dashboard',
    ONBOARDING: '/recruiter/onboarding',
    TEAM: '/recruiter/team',
    JOBS: '/recruiter/jobs',
    JOBS_NEW: '/recruiter/jobs/new',
    ATS: '/recruiter/ats',
    SETTINGS: '/recruiter/settings',
  },
  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    USER_NEW: '/admin/users/new',
    USER_DETAIL: (id: string) => `/admin/users/${id}`,
    JOBS: '/admin/jobs',
    JOB_DETAIL: (id: string) => `/admin/jobs/${id}`,
    APPLICATIONS: '/admin/applications',
    APPLICATION_DETAIL: (id: string) => `/admin/applications/${id}`,
    COMPANIES: '/admin/companies',
    COMPANY_DETAIL: (id: string) => `/admin/companies/${id}`,
    TRAINING_CENTERS: '/admin/training-centers',
    TRAINING_CENTER_NEW: '/admin/training-centers/new',
    TRAINING_CENTER_DETAIL: (id: string) => `/admin/training-centers/${id}`,
    PRIVATE_INSTITUTIONS: '/admin/private-institutions',
    PRIVATE_INSTITUTION_NEW: '/admin/private-institutions/new',
    PRIVATE_INSTITUTION_DETAIL: (id: string) => `/admin/private-institutions/${id}`,
    PRIVATE_INSTITUTION_OFFERINGS: '/admin/private-institution-offerings',
    TRAINING_FORMATIONS: '/admin/training-formations',
    TRAINING_EVENTS: '/admin/training-events',
  },
} as const;
